<?php

namespace ContainerGiirDlI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VduxounService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vduxoun' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vduxoun'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pizzaRepository' => ['privates', 'App\\Core\\Pizzas\\Repository\\PizzaRepository', 'getPizzaRepositoryService', true],
            'requestDto' => ['privates', 'App\\Api\\Pizzas\\Dto\\PizzaUpdateRequestDto', 'getPizzaUpdateRequestDtoService', true],
            'validationErrors' => ['privates', '.errored..service_locator.Vduxoun.Symfony\\Component\\Validator\\ConstraintViolationListInterface', NULL, 'Cannot autowire service ".service_locator.Vduxoun": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'pizzaRepository' => 'App\\Core\\Pizzas\\Repository\\PizzaRepository',
            'requestDto' => 'App\\Api\\Pizzas\\Dto\\PizzaUpdateRequestDto',
            'validationErrors' => 'Symfony\\Component\\Validator\\ConstraintViolationListInterface',
        ]);
    }
}
