<?php

namespace ContainerGiirDlI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Api\Pizzas\Controller\PizzaController' shared autowired service.
     *
     * @return \App\Api\Pizzas\Controller\PizzaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Api/Pizzas/Controller/PizzaController.php';

        $container->services['App\\Api\\Pizzas\\Controller\\PizzaController'] = $instance = new \App\Api\Pizzas\Controller\PizzaController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Api\\Pizzas\\Controller\\PizzaController', $container));

        return $instance;
    }
}
