<?php

namespace ContainerGiirDlI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaUpdateRequestDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Api\Pizzas\Dto\PizzaUpdateRequestDto' shared autowired service.
     *
     * @return \App\Api\Pizzas\Dto\PizzaUpdateRequestDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Api/Pizzas/Dto/PizzaUpdateRequestDto.php';

        return $container->privates['App\\Api\\Pizzas\\Dto\\PizzaUpdateRequestDto'] = new \App\Api\Pizzas\Dto\PizzaUpdateRequestDto();
    }
}
