<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQru9sV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQru9sV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQru9sV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQru9sV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQru9sV1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qru9sV1',
    'container.build_id' => '5c86f92e',
    'container.build_time' => 1623865860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQru9sV1');
